name: CI
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis_server: ["4", "5", "6", "7"]
        ruby: ["3.2", "3.3"]

    name: Redis server ${{ matrix.redis_server }} - Ruby ${{ matrix.ruby }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Set up Redis ${{ matrix.redis_server }}
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: ${{ matrix.redis_server }}

      - name: Run tests
        run: bin/test
